# Generated by Django 3.2.19 on 2023-06-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('COUNTRY_ID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('COUNTRY_NAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAPITAL_NAME', models.CharField(max_length=100)),
                ('CAPITAL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
